### ISSUE TITLE
Unexpected defaultFile behavior

### ISSUE THREAD

**Issue by englercj** [spalger/rcloader#2]
Encountering strange behavior with trying to use the following configuration:

```js
{ defaultFile: require.resolve('config-style'), lookup: true }
```

What I am trying to do is load a "base" `.jshintrc` file from a module installed with npm. Then override specific fields for whatever project to use perhaps a different value.

The first part works fine, it loads the specified `.jshintrc` file from the npm module. The strange part is that this is treated as the "most specific" file and it actually overrides my project specific files. This seems to be caused by this line:

https://github.com/spenceralger/rcloader/blob/master/index.js#L65
```js
      configFile = _.assign(configFile || {}, config);
```

Now, this makes sense when stepping out from the most-specific to least-specific .rc file the plugin finds; but not when config is the "defaultFile". What I would expect is it steps through all the .rc using normal logic, then just before returning the final value extends those values into the "defaultFile" values and returns that.

Maybe I am doing something wrong?

**For Example**

File Structure:
```
gulpfile.js
.jshintrc
node_modules/
|_ config-style/
  |_ .jshintrc
```

`.jshintrc` contents:
```json
{
    "strict": false,
    "browser": true
}
```

`config-style/.jshintrc` contents:
```json
{
    "strict": true,
    "eqeqeq": true
}
```

Expected output (with config: `{ defaultFile: require.resolve('config-style'), lookup: true }`):
```json
{
    "strict": false,
    "browser": true,
    "eqeqeq": true
}
```

Actual output (with config: `{ defaultFile: require.resolve('config-style'), lookup: true }`):
```json
{
    "strict": true,
    "browser": true,
    "eqeqeq": true
}
```

**Comment by yangmillstheory** [comment]
Can we close this due to #3 being merged?
