### ISSUE TITLE
rcloader.for outputting object instead of string

### ISSUE THREAD

**Issue by jaylinski** [spalger/rcloader#5]
hi there! i'm using the webpack/jshint-loader which includes your rcloader.
the loader didn't respect my `.jshintrc`, because the `rcloader.for` function does output an object instead of a string:
```javascript
// https://github.com/webpack/jshint-loader/blob/master/index.js
// console.log(this.resourcePath);
C:\xampp\htdocs\_www\frontend-webpack\src\js\main.js
```
```javascript
// https://github.com/webpack/jshint-loader/blob/master/index.js
// line 34
// var path = rcLoader.for(this.resourcePath);
// console.log(path);
{ '0': 'C',
  '1': ':',
  '2': '\\',
  '3': 'x',
  '4': 'a',
  '5': 'm',
  '6': 'p',
  '7': 'p',
  '8': '\\',
  '9': 'h',
  '10': 't',
  '11': 'd',
  '12': 'o',
  '13': 'c',
  '14': 's',
  '15': '\\',
  '16': '_',
  '17': 'w',
  '18': 'w',
  '19': 'w',
  '20': '\\',
  '21': 'f',
  '22': 'r',
  '23': 'o',
  '24': 'n',
  '25': 't',
  '26': 'e',
  '27': 'n',
  '28': 'd',
  '29': '-',
  '30': 'w',
  '31': 'e',
  '32': 'b',
  '33': 'p',
  '34': 'a',
  '35': 'c',
  '36': 'k',
  '37': '\\',
  '38': '.',
  '39': 'j',
  '40': 's',
  '41': 'h',
  '42': 'i',
  '43': 'n',
  '44': 't',
  '45': 'r',
  '46': 'c' }
```
anyone experiencing a similar issue?
my system:
win7 x64, nodejs 0.10.33
package.json:
"jshint-loader": "^0.8.1"
"rcloader": "0.1.x"

see referencing issue webpack/jshint-loader/issues/12

thx for having a look!

**Comment by Dashed** [comment]
Blame seems to point to this: https://github.com/spenceralger/rcloader/commit/355d6e771553c72b715f7df5d6259f6818cc987f

**Comment by sslash** [comment]
Having the same issue.

**Comment by nishp1** [comment]
It is this line: https://github.com/spenceralger/rcloader/commit/355d6e771553c72b715f7df5d6259f6818cc987f#diff-168726dbe96b3ce427e7fedce31bb0bcL65

Reverting that line fixes it, but that might break the test and overridable options feature added in recent release.

**Comment by englercj** [comment]
Oops, really hope this doesn't come down to removing overridable options >.<

Does treating a string with the old method and an object with the new method solve the issue and keep the tests passing?

**Comment by unindented** [comment]
Same issue here both with `jshint-loader` and with `jscs-loader`. They are passing `finderConfig` so that the loader returns the path:

```js
var rcLoader = new RcLoader('.jscsrc', null, {
  loader: function (path) {
    return path;
  }
});
```

@spenceralger how should we handle this?

**Comment by MoOx** [comment]
I'm concerned about this too.

**Comment by MoOx** [comment]
That why we should avoid 0.x version :/

**Comment by Dashed** [comment]
That's assuming maintainers follow semver. Some don't.

**Comment by MoOx** [comment]
Some should :)
